"""Generate test data for the STAGING database.

Writes SQL to supabase/seed-staging.sql. Every row it creates has an id
beginning with "seed-", and the script deletes those rows before inserting, so
running it again replaces the test data and never touches anything real.

It writes no email addresses: `created_by` is looked up from
`allowed_users.display_name`, so the file is safe in a public repository.

Usage:  python tools/seed_staging.py
"""
import datetime
import pathlib
import random

OUT = pathlib.Path(__file__).resolve().parent.parent / "supabase" / "seed-staging.sql"
DAYS = 14
# Days back from today that nobody logged, so averages have gaps to handle.
QUIET_DAYS = {4, 9}

SETTLE_NOTES = [
    "Went down without a fuss.",
    "Rocked for a few minutes, then self-settled.",
    "Grizzly at first, hand on chest for a minute.",
    "Took a while, stood up twice before lying down.",
    "Straight down after a story.",
]
WAKE_NOTES = [
    "Woke happy, chatting to himself.",
    "Woke crying, settled with a cuddle.",
    "Startled awake.",
    "",
    "",
]
FOODS = [
    ["Porridge", "Banana"], ["Sweet potato", "Avocado"], ["Weetabix", "Pear"],
    ["Scrambled egg", "Toast"], ["Chicken", "Carrot"], ["Yoghurt", "Blueberries"],
    ["Pasta", "Broccoli"],
]
NOTES_FEED = ["", "", "Fed on one side only.", "Took it all.", "Dozed off halfway."]


def sql_text(value):
    return "'" + str(value).replace("'", "''") + "'"


def who(name):
    """created_by without putting an address in the file."""
    return f"(select email from public.allowed_users where display_name = '{name}')"


def main():
    random.seed(17)
    today = datetime.date.today()
    lines = [
        "-- TEST DATA FOR THE STAGING DATABASE ONLY. Do not run this on the live one.",
        "-- Generated by tools/seed_staging.py. Every row's id starts with 'seed-'.",
        "",
        "delete from public.sleeps where id like 'seed-%';",
        "delete from public.feeds  where id like 'seed-%';",
        "delete from public.solids where id like 'seed-%';",
        "",
    ]

    for back in range(DAYS - 1, -1, -1):
        day = today - datetime.timedelta(days=back)
        if back in QUIET_DAYS:
            continue
        tag = day.isoformat()
        parent = "Dad" if back % 2 else "Mum"
        other = "Mum" if back % 2 else "Dad"

        # Night sleep, occasionally broken by a waking.
        bed_min = random.choice([0, 5, 10, 15, 20])
        wake_min = random.choice([0, 5, 10, 15])
        broken = back % 4 == 1
        if broken:
            lines.append(
                f"insert into public.sleeps (id, date, start_time, end_time, put_down, settle_notes, wake_notes, created_by) values "
                f"('seed-{tag}-n1', '{tag}', '19:{bed_min:02d}', '01:{wake_min:02d}', '18:{45 + (bed_min % 10):02d}', "
                f"{sql_text(random.choice(SETTLE_NOTES))}, {sql_text('Woke and needed resettling.')}, {who(parent)});"
            )
            lines.append(
                f"insert into public.sleeps (id, date, start_time, end_time, put_down, settle_notes, wake_notes, created_by) values "
                f"('seed-{tag}-n2', '{tag}', '01:{wake_min + 25:02d}', '06:{wake_min:02d}', '', "
                f"{sql_text('Back down after a short cuddle.')}, {sql_text(random.choice(WAKE_NOTES))}, {who(other)});"
            )
        else:
            lines.append(
                f"insert into public.sleeps (id, date, start_time, end_time, put_down, settle_notes, wake_notes, created_by) values "
                f"('seed-{tag}-n1', '{tag}', '19:{bed_min:02d}', '06:{wake_min:02d}', '18:{45 + (bed_min % 10):02d}', "
                f"{sql_text(random.choice(SETTLE_NOTES))}, {sql_text(random.choice(WAKE_NOTES))}, {who(parent)});"
            )

        # Naps: the morning one always, the afternoon one most days.
        lines.append(
            f"insert into public.sleeps (id, date, start_time, end_time, put_down, settle_notes, wake_notes, created_by) values "
            f"('seed-{tag}-d1', '{tag}', '09:{random.choice([15, 25, 35]):02d}', '10:{random.choice([30, 40, 50]):02d}', "
            f"'09:{random.choice([5, 10, 20]):02d}', '', '', {who(other)});"
        )
        if back % 5 != 3:
            lines.append(
                f"insert into public.sleeps (id, date, start_time, end_time, put_down, settle_notes, wake_notes, created_by) values "
                f"('seed-{tag}-d2', '{tag}', '13:{random.choice([20, 30, 45]):02d}', '14:{random.choice([40, 55]):02d}', "
                f"'13:{random.choice([10, 15, 25]):02d}', '', '', {who(parent)});"
            )

        # Feeds: mostly breast, one bottle on most days.
        times = ["07:00", "10:30", "14:30", "17:30", "21:00"]
        for index, time in enumerate(times):
            bottle = index == 3 and back % 3 != 0
            kind = "bottle" if bottle else "breast"
            amount = random.choice([150, 180, 210]) if bottle else None
            lines.append(
                f"insert into public.feeds (id, date, time, kind, amount_ml, notes, created_by) values "
                f"('seed-{tag}-f{index}', '{tag}', '{time}', '{kind}', "
                f"{amount if amount is not None else 'null'}, {sql_text(random.choice(NOTES_FEED))}, "
                f"{who(parent if index % 2 else other)});"
            )

        # Solids: lunch every day, tea most days.
        lines.append(
            f"insert into public.solids (id, date, time, foods, notes, created_by) values "
            f"('seed-{tag}-s1', '{tag}', '12:00', {sql_text(str(random.choice(FOODS)).replace(chr(39), chr(34)))}::jsonb, "
            f"'', {who(other)});"
        )
        if back % 3 != 2:
            lines.append(
                f"insert into public.solids (id, date, time, foods, notes, created_by) values "
                f"('seed-{tag}-s2', '{tag}', '17:00', {sql_text(str(random.choice(FOODS)).replace(chr(39), chr(34)))}::jsonb, "
                f"{sql_text(random.choice(['', '', 'Loved it.', 'Not interested today.']))}, {who(parent)});"
            )

    lines += [
        "",
        "-- Not asleep right now, and the settings the app reads.",
        "insert into public.app_state (key, value) values "
        "('status', '{\"asleep\":false,\"since\":null,\"settleNotes\":\"\",\"putDown\":\"\"}'::jsonb) "
        "on conflict (key) do update set value = excluded.value;",
        "insert into public.app_state (key, value) values "
        "('settings', '{\"dob\":\"2025-12-16\",\"nightStart\":\"19:00\",\"nightEnd\":\"06:00\",\"milkUnit\":\"ml\"}'::jsonb) "
        "on conflict (key) do update set value = excluded.value;",
        "",
    ]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(OUT.parent.parent)} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
